name: dlcov
description: check code coverage
version: 0.1.0
homepage: https://github.com/emanuel-braz/dlcov.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
