name: dlcov
description: A CLI to add code coverage threshold (CI/CD, git hooks, etc.)
version: 4.0.1
homepage: https://github.com/emanuel-braz/dlcov

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  lcov_parser: ^0.1.1

dev_dependencies:
  lints: ^1.0.1
  pedantic: ^1.10.0
  test: ^1.16.0

executables:
  dlcov: